In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("../data/2025-2026 NBA Player Stats - NBAstuffer.csv") 
df["PRA_Rank"] = df["P+R+A"].rank(ascending=False).astype(int)
df.head()

,RANK,NAME,TEAM,CUR,POS,AGE,GP,MpG,USG%,TO%,...,SpG,BpG,TOpG,P+R,P+A,P+R+A,VI,ORtg,DRtg,PRA_Rank
0,NaN,Jabari Smith Jr.,Hou,*,F,22.8,61,34.8,17.7,9.7,...,0.8,0.9,1.3,22.2,17.2,24.0,6.6,120.9,109.6,108
1,NaN,Alperen Sengun,Hou,*,C,23.6,58,33.4,27.1,17.4,...,1.2,1.1,3.3,29.1,26.2,35.2,12.4,115.3,105.3,22
2,NaN,Steven Adams,Hou,*,C,32.6,32,22.8,12.0,20.1,...,0.7,0.6,1.1,14.5,7.3,16.0,7.4,124.8,108.0,228
3,NaN,Kevin Durant,Hou,*,F,37.4,62,36.4,27.1,15.3,...,0.9,0.9,3.2,31.3,30.3,35.8,9.5,123.4,112.2,18
4,NaN,Amen Thompson,Hou,*,G-F,23.1,63,37.0,20.1,15.9,...,1.5,0.6,2.5,25.3,23.0,30.6,9.7,122.3,111.0,45

In [4]:
giannis = df[df['NAME'].str.contains("Giannis Antetokounmpo", case=False, na=False)
].copy()

giannis[["TEAM","POS","MpG","P+R+A","ORtg","DRtg"]]

    TEAM POS   MpG  P+R+A   ORtg   DRtg
202  Mil   F  29.0   42.6  126.4  109.4

In [5]:
peers = df[df["MpG"] > 20]

top_players = peers.sort_values(by="PRA_Rank", ascending=False).head(20)

giannis = df[df["NAME"] == "Giannis Antetokounmpo"]

print(giannis)

     RANK                   NAME TEAM CUR POS   AGE  GP   MpG  USG%   TO%  \
202   NaN  Giannis Antetokounmpo  Mil   *   F  31.3  34  29.0  36.3  16.7

     ...  SpG  BpG  TOpG   P+R   P+A  P+R+A    VI   ORtg   DRtg  PRA_Rank
202  ...  1.0  0.7   3.3  37.1  32.8   42.6  15.6  126.4  109.4         4

[1 rows x 31 columns]

In [6]:
metrics = ["MpG","PpG", "RpG", "ApG", "P+R+A", "PRA_Rank", "TS%", "USG%", "VI", "ORtg", "DRtg"]

comparison = peers.sort_values("PRA_Rank", ascending=True)[["NAME"] + metrics]

comparison

,NAME,MpG,PpG,RpG,ApG,P+R+A,PRA_Rank,TS%,USG%,VI,ORtg,DRtg
326,Nikola Jokic,34.6,28.6,12.5,10.4,51.6,1,0.679,31.3,17.9,135.4,107.3
35,Luka Doncic,35.5,32.5,7.9,8.4,48.8,2,0.613,37.5,14.6,119.9,110.0
13,Shai Gilgeous-Alexander,33.5,31.7,4.5,6.6,42.8,3,0.667,33.4,11.7,134.1,106.1
202,Giannis Antetokounmpo,29.0,27.4,9.8,5.4,42.6,4,0.666,36.3,15.6,126.4,109.4
116,Jalen Johnson,35.2,23.0,10.4,7.9,41.3,5,0.585,27.2,14.0,116.5,109.1
...,...,...,...,...,...,...,...,...,...,...,...,...
412,Sidy Cissoko,21.1,5.8,2.4,1.5,9.6,388,0.522,12.7,5.2,107.0,108.7
333,Spencer Jones,22.6,5.6,3.2,0.8,9.6,388,0.615,9.7,4.3,126.6,108.1
531,De'Andre Hunter,25.5,7.5,1.5,0.5,9.5,391,0.347,21.3,2.8,68.1,118.9
551,John Konchar,24.0,2.9,4.2,2.0,9.1,403,0.387,7.7,4.8,103.5,115.3
210,Taurean Prince,20.8,5.4,1.8,0.9,8.1,423,0.566,11.4,4.0,106.2,112.0

In [7]:
comparison.to_csv("top_players_comparison.csv", index=False)